---
- name: Make sure there is a key for rustdesk
  become: true
  block:
    - name: Get public key of rustdesk
      ansible.builtin.slurp:
        src: "{{ rustdesk__home }}/id_ed25519.pub"
      register: _rustdesk_pubkey
  rescue:
    - name: Run systemd setup to initially start rustdesk service and generate pubkeys
      ansible.builtin.include_tasks:
        file: 'install_systemd.yml'
      when: ansible_service_mgr == "systemd"

    - name: Get public key of rustdesk
      ansible.builtin.slurp:
        src: "{{ rustdesk__home }}/id_ed25519.pub"
      register: _rustdesk_pubkey

- name: Show Rustdesk Public Key
  ansible.builtin.debug:
    msg: "Pubkey: {{ _rustdesk_pubkey.content | b64decode }}"
    verbosity: 1
